theme: jekyll-theme-dinky
title: Projectseminar Computational Ethology
parts:
- caption: Part 1
  chapters:
  - file: readme.md
- caption: Part 2
  chapters:
  - file: readme.md
- caption: Part 3
  chapters:
  - file: readme.md
